- name: Variables
  hosts: web
  vars: #playlevel variables
   COURSE: "DevOps with AWS"
   DURATION: "120HRS"
   TRAINER: "SivaKumar Reddy"
  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"
  - name: print the information
    vars: #task level variables
      COURSE: "Ansible"
    ansible.builtin.debug:
     msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"