- name: Variables
  hosts: web
  vars:
   COURSE: "DevOps with AWS"
   DURATION: "120HRS"
   TRAINER: "SivaKumar Reddy"
  tasks:
  - name: print the information
    ansible.builtin.debug:
     msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"