- name: Variables from file
  hosts: web
  vars_files:
  - vars-file.yaml
  tasks:
   - name: print the course information
     ansible.builtin.debug:
       msg: "Hi,I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"
     

