- name: Variables from file
  hosts: web
  vars_files:
  - vars-files.yaml
  tasks:
   - name: vars from file
     ansible.builtin.debug:
       msg: "Hi,I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer is: {{TRAINER}}"
     

