- name: Variables from Arguments
  hosts: web
  
  tasks:
   - name: print the information
     ansible.builtin.debug:
        msg: "Hi {{NAME}}, Good {{GREETING}}"
        # for passing args we can use --extra-vars or -e