- name: Variables
  hosts: web
  
  # vars_files:
  # - vars-file.yaml

  # vars_prompt: #to get values from prompt
  # - name: COURSE
  #   prompt: Please enter the course name
  #   private: false #not confidential information and will be displayed in the terminal
  # - name: DURATION
  #   prompt: Please enter the duration
  #   private: false
  # - name: TRAINER
  #   prompt: Please enter the trainer name
  #   private: false

  vars: #playlevel variables,all taks will have access to this
    COURSE: "DevOps with AWS from play level"
    DURATION: "120HRS"
    TRAINER: "SivaKumar Reddy"

  tasks:
  - name: print the information
    vars: #task level variables,only for this task
       COURSE: "DevOps with AWS from task level"
       DURATION: "120HRS"
       TRAINER: "SivaKumar Reddy"
    ansible.builtin.debug:
     msg: "Hi, I am learning {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"

  #variables order of preference 

  #Command line Arguments
  #Task level variables
  #Files
  #Prompt
  #Play level
  #Inventory
  #Roles
  