#write a playbook to check if the given number is less than 10 or not
- name: Number less than 10 or not
  hosts: local
  connction: local

  vars_prompt:
  - name: Number
    prompt: Please enter a Number
    private: false #not confidential

  tasks:
  - name: Print if number less than 10
    ansible.builtin.debug:
      msg: "Given number {{Number}} is less than 10"
    when: Number < 10 #Conditional Expression

  - name: Print if number greater than or equal to 10
    ansible.builtin.debug:
      msg: "Given number {{Number}} is greater than or equal to 10"
    when: Number >= 10 #Conditional Expression
    