- name: loops package installation
  hosts: web
  become: yes
  
  tasks:
  - name: Installing packages
    ansible.builtin.package:
      name: "{{ item  }}"
      state: present
    loop: #list
    - mysql
    - nginx
    - postfix
    - httpd
