- name: loops package installation
  hosts: web
  become: yes

  tasks:
  - name: Installing packages
    ansible.builtin.package:
      name: {{ item.name }}
      state: {{ item.state }}
    loop: #map
    - { name: 'mysql', state: 'present' }
    - { name: 'nginx', state: 'absent' }
    - { name: 'postfix', state: 'absent' }
    - { name: 'httpd', state: 'present' }