#command is for simple commands and it will not get the shell environment
#shell is for complex ones like pipes,redirections etc and it gets the shell environment
 
- name: command vs shell
  hosts: local
  connection: local
 
  tasks:
  - name: execute the command
     #ansible.builtin.command: ls -ltr > /tmp/output.txt #it will not work because it is using redirections
    ansible.builtin.shell: ls -ltr > /tmp/output. 
    #log in to the server and executes command inside it whereas command module just issues the command. command is secure than 

  - name: check the process
    ansible.builtin.shell: ps -ef | grep ssh # this also will not work so we have to use shell
    register: output
  